
import { GoogleGenAI } from "@google/genai";
import { EraStyle } from "../types";

export const transformImage = async (
  base64Image: string,
  targetEra: EraStyle
): Promise<string> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key is missing.");

  const ai = new GoogleGenAI({ apiKey });
  
  // Extract mime type and base64 data
  const [mimePart, dataPart] = base64Image.split(',');
  const mimeType = mimePart.match(/:(.*?);/)?.[1] || 'image/png';

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: dataPart,
              mimeType: mimeType,
            },
          },
          {
            text: `You are a photographic era transformation expert. ${targetEra.prompt}. Make sure to realistically adjust the person's hairstyle, clothing, and the environment's lighting and camera texture to match exactly what a photo from that era looked like. Do not add any text or watermarks.`,
          },
        ],
      },
    });

    // Iterate through parts to find the image
    for (const candidate of response.candidates || []) {
      for (const part of candidate.content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image was generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
